/*
 * Chariot Payments API
 *
 * The Chariot Payments REST API.
 *
 * API version: v1
 * Contact: developers@givechariot.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package main

import (
	"log"

	"github.com/chariot-giving/agapay/pkg/network"
	"github.com/chariot-giving/agapay/pkg/openapi"
)

func main() {
	router := openapi.NewRouter()

	// initialize global variable
	network.PayeeDB = network.NewPayeeDatabase()

	log.Fatal(router.Run(":8080"))
}
