/*
 * Chariot Payments API
 *
 * The Chariot Payments REST API.
 *
 * API version: v1
 * Contact: developers@givechariot.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"net/http"
	"time"

	"github.com/chariot-giving/agapay/pkg/bank"
	"github.com/gin-gonic/gin"
)

// GetRecipient - Retrieve a recipient
func GetRecipient(c *gin.Context) {
	id := c.Param("id")

	// TODO: do we store and retrieve recipients as entities within the Increase.com API/models?
	entity, err := bank.IncreaseClient.Entities.Get(c, id)
	if err != nil {
		c.JSON(http.StatusNotFound, gin.H{"error": err.Error()})
		return
	}

	recipient := Recipient{
		Id:        entity.ID,
		Name:      entity.Description,
		Ein:       entity.Corporation.TaxIdentifier,
		Primary:   true,
		Status:    string(entity.Status),
		CreatedAt: time.Now(),
	}

	c.JSON(http.StatusOK, &recipient)
}

// ListRecipients - List recipients
func ListRecipients(c *gin.Context) {
	// TODO: do we store and retrieve recipients as entities within the Increase.com API/models?
	// If so, there's not a great way to list and filter recipients by EIN, so we may need to
	// implement this ourselves.
	c.JSON(http.StatusOK, gin.H{})
}
