/*
 * Chariot Payments API
 *
 * The Chariot Payments REST API.
 *
 * API version: v1
 * Contact: developers@givechariot.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"net/http"
	"strconv"

	"github.com/chariot-giving/agapay/pkg/bank"
	"github.com/chariot-giving/agapay/pkg/network"
	"github.com/gin-gonic/gin"
	"github.com/increase/increase-go"
)

// CreatePayment - Create a payment
func CreatePayment(c *gin.Context) {
	payment := new(Payment)
	if err := c.ShouldBindJSON(payment); err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"error": err.Error()})
		return
	}

	electronicAccount, err := network.PayeeDB.GetPayeeElectronicAccount(payment.RecipientId)
	if err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"error": err.Error()})
		return
	}

	transfer, err := bank.IncreaseClient.RealTimePaymentsTransfers.New(c, increase.RealTimePaymentsTransferNewParams{
		CreditorName:             increase.String(electronicAccount.Name),
		Amount:                   increase.Int(payment.Amount),
		RemittanceInformation:    increase.String(payment.Description),
		SourceAccountNumberID:    increase.String(payment.AccountId),
		DestinationAccountNumber: increase.String(electronicAccount.AccountNumber),
		DestinationRoutingNumber: increase.String(electronicAccount.RoutingNumber),
	})
	if err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"error": err.Error()})
		return
	}

	payment.Id = transfer.ID
	payment.TransactionId = transfer.TransactionID
	payment.Status = string(transfer.Status)

	c.JSON(http.StatusOK, payment)
}

// GetPayment - Retrieve a payment
func GetPayment(c *gin.Context) {
	id := c.Param("id")

	transfer, err := bank.IncreaseClient.RealTimePaymentsTransfers.Get(c, id)
	if err != nil {
		c.JSON(http.StatusNotFound, gin.H{"error": err.Error()})
		return
	}

	// TODO: source recipient + chariot ID from database
	payment := Payment{
		Id:            transfer.ID,
		AccountId:     transfer.AccountID,
		Amount:        transfer.Amount,
		Description:   transfer.RemittanceInformation,
		TransactionId: transfer.TransactionID,
		Status:        string(transfer.Status),
		RecipientId:   "",
		ChariotId:     "",
	}

	c.JSON(http.StatusOK, &payment)
}

// ListPayments - List payments
func ListPayments(c *gin.Context) {
	limitQuery := c.DefaultQuery("limit", "100")
	limit, err := strconv.ParseInt(limitQuery, 10, 64)
	if err != nil {
		limit = 100
	}
	cursor := c.DefaultQuery("cursor", "")

	accountId, ok := c.GetQuery("account_id")
	if !ok {
		c.JSON(http.StatusBadRequest, gin.H{"error": "account_id is required"})
		return
	}

	// TODO: filter by recipient ID in our database first
	// recipientId := c.DefaultQuery("recipient_id", "")

	response, err := bank.IncreaseClient.RealTimePaymentsTransfers.List(c, increase.RealTimePaymentsTransferListParams{
		AccountID: increase.String(accountId),
		Limit:     increase.Int(limit),
		Cursor:    increase.String(cursor),
	})
	if err != nil {
		c.JSON(http.StatusNotFound, gin.H{"error": err.Error()})
		return
	}

	payments := make([]Payment, len(response.Data))
	for i, transfer := range response.Data {
		payments[i] = Payment{
			Id:            transfer.ID,
			AccountId:     transfer.AccountID,
			Amount:        transfer.Amount,
			Description:   transfer.RemittanceInformation,
			TransactionId: transfer.TransactionID,
			Status:        string(transfer.Status),
			RecipientId:   "",
			ChariotId:     "",
		}
	}

	paymentList := PaymentList{
		Data: payments,
		Paging: Pagination{
			Total: int32(len(response.Data)),
			Cursors: PaginationCursors{
				Before: cursor,
				After:  response.NextCursor,
			},
		},
	}

	c.JSON(http.StatusOK, &paymentList)
}
