/*
 * Chariot Payments API
 *
 * The Chariot Payments REST API.
 *
 * API version: v1
 * Contact: developers@givechariot.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"time"
)

// Transfer - A transfer moves funds between accounts using ACH.
type Transfer struct {

	// The unique identifier for the transfer
	Id string `json:"id,omitempty"`

	// The identifier for the Chariot account that will send the transfer.
	AccountId string `json:"account_id"`

	// A description of the transfer. Remittance information for the transfer that will show on the recipient's bank statement.
	Description string `json:"description"`

	// The transfer amount in USD cents. A positive amount originates a credit transfer pushing funds to the receiving account. A negative amount originates a debit transfer pulling funds from the receiving account.
	Amount int64 `json:"amount"`

	// The account number for the destination account.
	AccountNumber string `json:"account_number"`

	// The American Bankers' Association (ABA) Routing Transit Number (RTN) for the destination account.
	RoutingNumber string `json:"routing_number"`

	// The type of the account to which the transfer will be sent.
	Funding string `json:"funding,omitempty"`

	// The unique identifier for the transaction funding the transfer.
	TransactionId string `json:"transaction_id,omitempty"`

	// The status of the transfer
	Status string `json:"status,omitempty"`

	// The date and time the transfer was created
	CreatedAt time.Time `json:"created_at,omitempty"`
}
