/*
 * Chariot Payments API
 *
 * The Chariot Payments REST API.
 *
 * API version: v1
 * Contact: developers@givechariot.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// TransferList - A list of transfers
type TransferList struct {

	// The list of transfers
	Data []Transfer `json:"data"`

	Paging Pagination `json:"paging"`
}
