/*
 * Chariot Payments API
 *
 * The Chariot Payments REST API.
 *
 * API version: v1
 * Contact: developers@givechariot.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// RecipientList - A list of recipients
type RecipientList struct {

	// The list of recipients
	Data []Recipient `json:"data,omitempty"`

	Paging Pagination `json:"paging,omitempty"`
}
