/*
 * Chariot Payments API
 *
 * The Chariot Payments REST API.
 *
 * API version: v1
 * Contact: developers@givechariot.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type CreateRecipientRequest struct {

	// The name of the recipient
	Name string `json:"name,omitempty"`

	// The Employer Identification Number (EIN) for the recipient.
	Ein string `json:"ein,omitempty"`

	// Indicates whether the recipient is the primary recipient for the EIN. Only one recipient can be the primary recipient for an EIN. 
	Primary bool `json:"primary,omitempty"`

	BankAddress RecipientBankAddress `json:"bank_address,omitempty"`
}
