/*
 * Chariot Payments API
 *
 * The Chariot Payments REST API.
 *
 * API version: v1
 * Contact: developers@givechariot.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// AccountBalance - The balance of an account
type AccountBalance struct {

	// The unique identifier for the account
	AccountId string `json:"account_id,omitempty"`

	// The Account's current balance, representing the sum of all posted Transactions on the Account.
	CurrentBalance int64 `json:"current_balance"`

	// The Account's available balance, representing the current balance less any open Pending Transactions on the Account.
	AvailableBalance int64 `json:"available_balance"`
}
