/*
 * Chariot Payments API
 *
 * The Chariot Payments REST API.
 *
 * API version: v1
 * Contact: developers@givechariot.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"time"
)

// ApiError - An API error
type ApiError struct {

	// The date and time the error occurred
	Timestamp time.Time `json:"timestamp,omitempty"`

	// The HTTP status code
	Status int32 `json:"status,omitempty"`

	// The HTTP status message
	Error string `json:"error,omitempty"`

	// The error message
	Message string `json:"message,omitempty"`
}
