/*
 * Chariot Payments API
 *
 * The Chariot Payments REST API.
 *
 * API version: v1
 * Contact: developers@givechariot.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// TransactionList - A list of transactions
type TransactionList struct {

	// The list of transactions
	Data []Transaction `json:"data,omitempty"`

	Paging Pagination `json:"paging,omitempty"`
}
