/*
 * Chariot Payments API
 *
 * The Chariot Payments REST API.
 *
 * API version: v1
 * Contact: developers@givechariot.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"log"
	"net/http"
	"os"

	"github.com/chariot-giving/agapay/pkg/logger"
	"github.com/chariot-giving/agapay/pkg/middleware"
	"github.com/gin-gonic/gin"
)

// Route is the information for every URI.
type Route struct {
	// Name is the name of this Route.
	Name string
	// Method is the string for the HTTP method. ex) GET, POST etc..
	Method string
	// Pattern is the pattern of the URI.
	Pattern string
	// HandlerFunc is the handler function of this route.
	HandlerFunc gin.HandlerFunc
}

// Routes is the list of the generated Route.
type Routes []Route

// NewRouter returns a new router.
func NewRouter() *gin.Engine {
	router := gin.Default()

	logLevel := os.Getenv("LOG_LEVEL")
	if logLevel == "" {
		logLevel = "info"
	}
	zapLogger, err := logger.Init(logLevel, "2006-01-02 15:04:05.000 MST")
	if err != nil {
		log.Fatalf("failed to initialize logger: %v", err)
	}
	defer logger.Flush() // flushes buffer on exit

	// add middleware
	middlewares := []gin.HandlerFunc{
		middleware.RequestIDMiddleware(),
		middleware.LoggingMiddleware(zapLogger),
		middleware.ApiKeyAuth(),
	}
	router.Use(middlewares...)

	for _, route := range routes {
		switch route.Method {
		case http.MethodGet:
			router.GET(route.Pattern, route.HandlerFunc)
		case http.MethodPost:
			router.POST(route.Pattern, route.HandlerFunc)
		case http.MethodPut:
			router.PUT(route.Pattern, route.HandlerFunc)
		case http.MethodPatch:
			router.PATCH(route.Pattern, route.HandlerFunc)
		case http.MethodDelete:
			router.DELETE(route.Pattern, route.HandlerFunc)
		}
	}

	return router
}

// Index is the index handler.
func Index(c *gin.Context) {
	c.String(http.StatusOK, "Hello World!")
}

var routes = Routes{
	{
		"Index",
		http.MethodGet,
		"/",
		Index,
	},

	{
		"CreateAccount",
		http.MethodPost,
		"/accounts",
		CreateAccount,
	},

	{
		"GetAccount",
		http.MethodGet,
		"/accounts/:id",
		GetAccount,
	},

	{
		"GetAccountBalances",
		http.MethodGet,
		"/accounts/:id/balances",
		GetAccountBalances,
	},

	{
		"CreatePayment",
		http.MethodPost,
		"/payments",
		CreatePayment,
	},

	{
		"GetPayment",
		http.MethodGet,
		"/payments/:id",
		GetPayment,
	},

	{
		"ListPayments",
		http.MethodGet,
		"/payments",
		ListPayments,
	},

	{
		"GetRecipient",
		http.MethodGet,
		"/recipients/:id",
		GetRecipient,
	},

	{
		"ListRecipients",
		http.MethodGet,
		"/recipients",
		ListRecipients,
	},

	{
		"GetTransfer",
		http.MethodGet,
		"/transfers/:id",
		GetTransfer,
	},

	{
		"ListTransfers",
		http.MethodGet,
		"/transfers",
		ListTransfers,
	},

	{
		"TransferFunds",
		http.MethodPost,
		"/transfers",
		TransferFunds,
	},
}
