/*
 * Chariot Payments API
 *
 * The Chariot Payments REST API.
 *
 * API version: v1
 * Contact: developers@givechariot.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"net/http"
	"time"

	"github.com/chariot-giving/agapay/pkg/bank"
	"github.com/chariot-giving/agapay/pkg/cerr"
	"github.com/gin-gonic/gin"
	"github.com/increase/increase-go"
)

// GetAccountBalances - Retrieve account balances
func GetAccountBalances(c *gin.Context) {
	accountId := c.Param("id")

	balanceLookup, err := bank.IncreaseClient.BalanceLookups.Lookup(c, increase.BalanceLookupLookupParams{
		AccountID: increase.String(accountId),
		AtTime:    increase.Null[time.Time](),
	})
	if err != nil {
		c.JSON(http.StatusBadGateway, cerr.NewBadGatewayError("error retrieving account balances", err))
		return
	}

	balance := AccountBalance{
		AccountId:        balanceLookup.AccountID,
		CurrentBalance:   balanceLookup.CurrentBalance,
		AvailableBalance: balanceLookup.AvailableBalance,
	}

	c.JSON(http.StatusOK, &balance)
}
