/*
 * Chariot Payments API
 *
 * The Chariot Payments REST API.
 *
 * API version: v1
 * Contact: developers@givechariot.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// PaginationCursors - The cursors for the next and previous pages
type PaginationCursors struct {

	// The cursor for the previous page
	Before string `json:"before,omitempty"`

	// The cursor for the next page
	After string `json:"after,omitempty"`
}
