/*
 * Chariot Payments API
 *
 * The Chariot Payments REST API.
 *
 * API version: v1
 * Contact: developers@givechariot.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// AccountList - A list of accounts
type AccountList struct {

	// The list of accounts
	Data []Account `json:"data,omitempty"`

	Paging Pagination `json:"paging,omitempty"`
}
