/*
 * Chariot Payments API
 *
 * The Chariot Payments REST API.
 *
 * API version: v1
 * Contact: developers@givechariot.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"time"
)

// Transaction - Transactions are the immutable additions and removals of money from your account. They're the equivalent of line items on your bank statement.
type Transaction struct {

	// The unique identifier for the transaction
	Id string `json:"id"`

	// The unique identifier for the account
	AccountId string `json:"account_id"`

	// The transaction amount in USD cents. A positive amount represents a credit to the account. A negative amount represents a debit to the account.
	Amount int64 `json:"amount"`

	// An informational message describing this transaction. Use the fields in source to get more detailed information. This field appears as the line-item on the statement.
	Description string `json:"description"`

	// The date and time the transaction was created
	CreatedAt time.Time `json:"created_at,omitempty"`
}
