/*
 * Chariot Payments API
 *
 * The Chariot Payments REST API.
 *
 * API version: v1
 * Contact: developers@givechariot.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"time"
)

// Payment - A payment moves funds from a Chariot account to a verified nonprofit recipient.
type Payment struct {

	// The unique identifier for the payment
	Id string `json:"id,omitempty"`

	// The identifier for the Chariot account that will send the payment.
	AccountId string `json:"account_id"`

	// The payment amount in USD cents. Must be a positive amount.
	Amount int64 `json:"amount"`

	// The payment rail to use for the payment. Currently only ACH and RTP is supported.
	PaymentRail string `json:"payment_rail"`

	// The identifier for the organization that will receive the payment.
	RecipientId string `json:"recipient_id"`

	// A description of the payment. Remittance information for the payment that will show on the recipient's bank statement.
	Description string `json:"description"`

	// The unique identifier for the initiated payment from Chariot. This is useful if the payment was initiated by Chariot and allows for end-to-end tracking of the payment for the donor.
	ChariotId string `json:"chariot_id,omitempty"`

	// The unique identifier for the transaction funding the payment.
	TransactionId string `json:"transaction_id,omitempty"`

	// The status of the payment
	Status string `json:"status,omitempty"`

	// The date and time the payment was created
	CreatedAt time.Time `json:"created_at,omitempty"`
}
