/*
 * Chariot Payments API
 *
 * The Chariot Payments REST API.
 *
 * API version: v1
 * Contact: developers@givechariot.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// PaymentList - A list of payments
type PaymentList struct {

	// The list of payments
	Data []Payment `json:"data,omitempty"`

	Paging Pagination `json:"paging,omitempty"`
}
