/*
 * Chariot Payments API
 *
 * The Chariot Payments REST API.
 *
 * API version: v1
 * Contact: developers@givechariot.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"net/http"

	"github.com/chariot-giving/agapay/pkg/auth"
	"github.com/chariot-giving/agapay/pkg/cerr"
	"github.com/chariot-giving/agapay/pkg/core"
	"github.com/chariot-giving/agapay/pkg/logger"
	"github.com/chariot-giving/agapay/pkg/telemetry"
	"github.com/gin-gonic/gin"
	"go.uber.org/zap"
)

// Route is the information for every URI.
type Route struct {
	// Name is the name of this Route.
	Name string
	// Method is the string for the HTTP method. ex) GET, POST etc..
	Method string
	// Pattern is the pattern of the URI.
	Pattern string
}

// Routes is the list of the generated Route.
type Routes []Route

// NewRouter returns a new router.
func NewRouter(server *core.AgapayServer) *gin.Engine {
	router := gin.Default()
	router.NoRoute(func(c *gin.Context) {
		c.JSON(404, cerr.NewNotFoundError("route not found", nil))
	})

	// add middleware
	middlewares := []gin.HandlerFunc{
		telemetry.RequestIDMiddleware(),
		logger.LoggingMiddleware(zap.L()),
		cerr.ErrorHandler(),
		auth.ApiKeyAuth(),
	}
	router.Use(middlewares...)

	openApiServer := openAPIServer{
		core: server,
	}

	for _, route := range routes {
		handler := openApiServer.getHandler(route.Name)
		switch route.Method {
		case http.MethodGet:
			router.GET(route.Pattern, handler)
		case http.MethodPost:
			router.POST(route.Pattern, handler)
		case http.MethodPut:
			router.PUT(route.Pattern, handler)
		case http.MethodPatch:
			router.PATCH(route.Pattern, handler)
		case http.MethodDelete:
			router.DELETE(route.Pattern, handler)
		}
	}

	return router
}

// Index is the index handler.
func Index(c *gin.Context) {
	c.String(http.StatusOK, "Hello World!")
}

var routes = Routes{
	{
		"Index",
		http.MethodGet,
		"/",
	},

	{
		"CreateAccount",
		http.MethodPost,
		"/accounts",
	},

	{
		"GetAccount",
		http.MethodGet,
		"/accounts/:id",
	},

	{
		"GetAccountDetails",
		http.MethodGet,
		"/accounts/:id/details",
	},

	{
		"ListAccounts",
		http.MethodGet,
		"/accounts",
	},

	{
		"GetAccountBalances",
		http.MethodGet,
		"/accounts/:id/balances",
	},

	{
		"CreatePayment",
		http.MethodPost,
		"/payments",
	},

	{
		"GetPayment",
		http.MethodGet,
		"/payments/:id",
	},

	{
		"ListPayments",
		http.MethodGet,
		"/payments",
	},

	{
		"CreateRecipient",
		http.MethodPost,
		"/recipients",
	},

	{
		"GetRecipient",
		http.MethodGet,
		"/recipients/:id",
	},

	{
		"ListRecipients",
		http.MethodGet,
		"/recipients",
	},

	{
		"GetTransaction",
		http.MethodGet,
		"/transactions/:id",
	},

	{
		"ListTransactions",
		http.MethodGet,
		"/transactions",
	},

	{
		"GetTransfer",
		http.MethodGet,
		"/transfers/:id",
	},

	{
		"ListTransfers",
		http.MethodGet,
		"/transfers",
	},

	{
		"TransferFunds",
		http.MethodPost,
		"/transfers",
	},
}
