openapi: 3.0.0
info:
  title: Chariot API
  version: "v1"
  description: The Chariot REST API. Please see https://givechariot.readme.io/reference/overview for more details.
  contact:
    name: Chariot Development Team
    url: https://www.givechariot.com/contact
    email: partners@givechariot.com
  termsOfService: https://www.givechariot.com/legal-nonprofit
servers:
  - url: https://sandboxapi.givechariot.com
    description: Sandbox
  - url: https://api.givechariot.com
    description: Production
paths:
  /v1/nonprofit/{ein}:
    get:
      summary: Get nonprofit by EIN
      description: |-
        Retrieves a nonprofit organization by an [Employee Identification Number](https://www.irs.gov/charities-non-profits/employer-identification-number) (EIN).
        The EIN is a unique number that identifies the organization to the Internal Revenue Service (IRS).

        In the case that the organization does not exist within Chariot's system, you can create one by calling the [Create Nonprofit](/api/nonprofits/create) API endpoint.
      operationId: get-nonprofit-by-ein
      tags:
        - Nonprofits
      security:
        - auth0:
            - "read:nonprofits"
  /v1/nonprofits:
    post:
      summary: Create nonprofit
      description: |-
        Create a nonprofit organization.

        This is useful for integration partners to use after a nonprofit consents to use the Chariot payment option on their donation forms.

        <Tip>
        If a nonprofit does not already exist for the EIN, this will return a `201 Created` status.
        If a nonprofit already exists for the given EIN on the system, this will return a `200 OK` status.
        </Tip>

        <Warning>
        Handling errors:
        - If the nonprofit does not exist within Chariot's database, a `404 Not Found` status is returned.
        - If the nonprofit exists but does not pass Chariot's compliance checks, a `412 Precondition Failed` status is returned with a reason.
        </Warning>
      operationId: create-nonprofit
      tags:
        - Nonprofits
      security:
        - auth0:
            - "create:nonprofits"
  /v1/nonprofits/{id}:
    get:
      summary: Get nonprofit
      description: |-
        Retrieves the nonprofit organization with the given ID.
      operationId: get-nonprofit-by-id
      tags:
        - Nonprofits
      security:
        - auth0:
            - "read:nonprofits"
  /v1/connects:
    post:
      summary: Create Connect
      description: |-
        Get an existing connect or create a new connect for an existing nonprofit organization.

        The returned Connect can be used to integrate the client-side Chariot Connect component using the `id` property (CID) and also query for data generated from the Chariot Connect instance from the Chariot API using the `x-chariot-api-key` header parameter.

        <Note>
        Only one Connect object can be created per Nonprofit.
        If one already exists, this will return a `200 OK` status with the existing object.
        </Note>
      operationId: create-connect
      tags:
        - Connects
      security:
        - auth0:
            - "create:connects"
  /v1/connects/{id}:
    get:
      summary: Get Connect
      description: |-
        Retrieve a connect with the given ID.
      operationId: get-connect
      tags:
        - Connects
      security:
        - auth0:
            - "read:connects"
  /v1/grants:
    get:
      summary: List Grants
      description: |-
        Returns a list of all grants for a given Connect. This API allows for paginating over many results.
      operationId: list-grants
      tags:
        - Grants
      security:
        - auth0:
            - "read:grants"
    post:
      summary: Create Grant
      description: |-
        Create and submit a new grant. This should be used to capture a grant intent from an authorized DAFpay workflow session and submit the grant request to the DAF sponsor.

        <Warning>
        Error handling:
        - The grant must be captured within 15 minutes of authorization otherwise the request will return status `410 Gone`.
        - A grant can only be captured once from any given workflow session so any duplicate requests will return status `409 Conflict`.
        - The amount must be in whole dollar increments (rounded to the nearest hundred) as currently DAFs only accept whole dollar grants otherwise the request will return status `400 Bad Request`.
        - The amount must be greater than or equal to the minimum grant amount for the DAF otherwise the request will return status `400 Bad Request`.
        - The amount must be less than or equal to the user's DAF account balance otherwise the request will return status `400 Bad Request`.
        </Warning>
      operationId: create-grant
      tags:
        - Grants
      security:
        - auth0:
            - "create:grants"
  /v1/grants/{id}:
    get:
      summary: Get Grant
      description: |-
        Retrieve a grant with the given ID.
      operationId: get-grant
      tags:
        - Grants
      security:
        - auth0:
            - "read:grants"
    patch:
      summary: Update Grant
      description: |-
        Update a grant object with the given ID.
        This can be used to update the status or acknowledgement of the grant.
      operationId: update-grant
      tags:
        - Grants
      security:
        - auth0:
            - "update:grants"
  /v1/recurring_grants:
    get:
      summary: List Recurring Grants
      description: |-
        Returns a list of all recurring grants for a given Connect. This API allows for paginating over many results.
      operationId: list-recurring-grants
      tags:
        - recurring_grants
      security:
        - auth0:
            - "read:recurring_grants"
    post:
      summary: Create Recurring Grant
      description: |-
        Create and submit a new recurring grant. This should be used to capture a recurring grant intent from an authorized DAFpay workflow session and submit the recurring grant request to the DAF sponsor.

        <Warning>
        Error handling:
        - The recurring grant must be captured within 15 minutes of authorization otherwise the request will return status `410 Gone`.
        - A recurring grant can only be captured once from any given workflow session so any duplicate requests will return status `409 Conflict`.
        - The amount must be in whole dollar increments (rounded to the nearest hundred) as currently DAFs only accept whole dollar grants otherwise the request will return status `400 Bad Request`.
        - The amount must be greater than or equal to the minimum grant amount for the DAF otherwise the request will return status `400 Bad Request`.
        - The amount must be less than or equal to the user's DAF account balance otherwise the request will return status `400 Bad Request`.
        </Warning>
      operationId: create-recurring-grant
      tags:
        - recurring_grants
      security:
        - auth0:
            - "create:recurring_grants"
  /v1/recurring_grants/{id}:
    get:
      summary: Get Recurring Grant
      description: |-
        Retrieve a recurring grant with a given ID.
      operationId: get-recurring-grant
      tags:
        - recurring_grants
      security:
        - auth0:
            - "read:recurring_grants"
  /v1/unintegrated_grants:
    get:
      summary: List Unintegrated Grants
      description: |-
        Returns a list of all unintegrated grants for a given Connect. This API allows for paginating over many results.
      operationId: list-unintegrated-grants
      tags:
        - unintegrated_grants
      security:
        - auth0:
            - "read:grants"
  /v1/unintegrated_grants/{id}:
    get:
      summary: Get Unintegrated Grant
      description: |-
        Retrieve an unintegrated grant with a given ID.
      operationId: get-unintegrated-grant
      tags:
        - unintegrated_grants
      security:
        - auth0:
            - "read:grants"
    patch:
      summary: Update Unintegrated Grant
      description: |-
        Update an unintegrated grant object with the given ID.
        This can be used to update the status or acknowledgement of the unintegrated grant.
      operationId: update-unintegrated-grant
      tags:
        - unintegrated_grants
      security:
        - auth0:
            - "update:grants"
  /v1/dafs:
    get:
      summary: List Donor Advised Funds
      description: |-
        Returns a list of all Donor Advised Funds within Chariot's system. This API allows for paginating over many results.

        <Note>
        If there are DAFs missing from the list, please contact support at support@givechariot.com.
        </Note>
      operationId: list-dafs
      tags:
        - Donor Advised Funds
  /v1/dafs/{id}:
    get:
      summary: Get Donor Advised Fund
      description: |-
        Retrieve a DAF with a given ID.
      operationId: get-daf
      tags:
        - Donor Advised Funds
  /v1/events:
    get:
      summary: List Events
      description: |-
        List all events corresponding to your Chariot account.
      operationId: listEvents
      tags:
        - Events
      security:
        - auth0:
            - "read:events"
  /v1/events/{id}:
    get:
      summary: Get Event
      description: |-
        Retrieve an event with the given ID.
      operationId: getEvent
      tags:
        - Events
      security:
        - auth0:
            - "read:events"
  /v1/event_subscriptions:
    post:
      summary: Create an Event Subscription
      description: |-
        Create an event subscription corresponding to your Chariot account.
      operationId: createEventSubscription
      tags:
        - Event Subscriptions
      security:
        - auth0:
            - "create:event_subscriptions"
    get:
      summary: List Event Subscriptions
      description: |-
        List all event subscriptions corresponding to your Chariot account.
      operationId: listEventSubscriptions
      tags:
        - Event Subscriptions
      security:
        - auth0:
            - "read:event_subscriptions"
  /v1/event_subscriptions/{id}:
    get:
      summary: Get an Event Subscription
      description: |-
        Retrieve an event subscription with the given ID.
      operationId: getEventSubscription
      tags:
        - Event Subscriptions
      security:
        - auth0:
            - "read:event_subscriptions"
    patch:
      summary: Update an Event Subscription
      description: |-
        Update an event subscription with the given ID.
      operationId: updateEventSubscription
      tags:
        - Event Subscriptions
      security:
        - auth0:
            - "update:event_subscriptions"
  /files:
    post:
      summary: Create a file
      description: |
        Create & upload a file.
        To upload a file to Chariot, you'll need to send a request of Content-Type multipart/form-data.
        The request should contain the file you would like to upload, as well as the parameters for creating a file.
      operationId: uploadFile
      tags:
        - files
      security:
        - bearerAuth: []
    get:
      summary: List files
      description: |
        List files.
      operationId: listFiles
      tags:
        - files
      security:
        - bearerAuth: []
  /files/{id}:
    get:
      summary: Retrieve a file
      description: |
        Get a file by its unique identifier.
      operationId: getFile
      tags:
        - files
      security:
        - bearerAuth: []
  /accounts:
    get:
      summary: List accounts
      description: |
        Returns a list of accounts.
      operationId: listAccounts
      tags:
        - Accounts
      security:
        - bearerAuth: []
  /accounts/{id}:
    get:
      summary: Retrieve an account.
      description: |
        Get an account by its unique identifier.
      operationId: getAccount
      tags:
        - Accounts
      security:
        - bearerAuth: []
  /transactions:
    post:
      summary: Create a transaction
      description: |
        This endpoint is used to send transactional data to a nonprofit account for a payment that happens outside of Chariot.
        Open payment networks that depend on the Federal Reserve are often very limited in terms of the data that can be sent with a payment.
        This endpoint allows you to send additional data to the account that can be used to reconcile the payment.
      operationId: createTransaction
      tags:
        - Transactions
      security:
        - bearerAuth: []
    get:
      summary: List transactions
      description: |
        List transactions. 
      operationId: listTransactions
      tags:
        - Transactions
      security:
        - bearerAuth: []
  /transactions/{id}:
    get:
      summary: Retrieve a transaction
      description: |
        Get a transaction by its unique identifier.
      operationId: getTransaction
      tags:
        - Transactions
      security:
        - bearerAuth: []
  /payments:
    post:
      summary: Create a payment
      description: |
        Create a payment to send money to a nonprofit account.
        In order to use this endpoint, you must be a registered Chariot Payments partner.
      operationId: createPayment
      tags:
        - Payments
      security:
        - bearerAuth: []
    get:
      summary: List payments
      description: |
        Returns a list of payments.
      operationId: listPayments
      tags:
        - Payments
      security:
        - bearerAuth: []
  /payments/{id}:
    get:
      summary: Retrieve a payment
      description: |
        Get a payment by its unique identifier.
        This endpoint is used to retrieve a payment by its unique identifier.
      operationId: getPayment
      tags:
        - Payments
      security:
        - bearerAuth: []
components:
  securitySchemes:
    auth0:
      type: oauth2
      description: This API uses OAuth2 with the client credentials flow.
      flows:
        clientCredentials:
          tokenUrl: https://login.givechariot.com/oauth/token
          scopes:
            "create:nonprofits": create a nonprofit and user
            "read:nonprofits": read all nonprofits
            "create:connects": create any connect, principle does not need to be associated with nonprofit
            "read:connects": read all connects for a nonprofit
            "create:grants": create a grant from a workflow session
            "read:grants": "read grants"
            "update:grants": "update grants"
            "read:events": "read events"
            "create:event_subscriptions": "create event subscriptions"
            "read:event_subscriptions": "read event subscriptions"
            "update:event_subscriptions": "update event subscriptions"
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: Opaque